name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "acr20241022mark"
  AZURE_CONTAINER_REGISTRY: "acr20241022mark.azurecr.io"
  CONTAINER_NAME: "hello-world"
  
on:
  push:
   branches: "master"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildContainerImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
          # Container registry password
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          # Container registry server url
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          file: "./Dockerfile"
      
  # deployToAKS:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: 
  #       uses: 
    
